# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:

name: "PHPUnit-tests"

permissions:
  contents: "read"

jobs:
  phpunit:
    name: "Tests php ${{ matrix.php-version }}"

    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          # extensions: curl, mbstring, zip
          # ini-values: memory_limit=-1
          tools: "composer:v2"

      - name: "Install Dependencies"
        run: "composer install"

      - name: "Run tests with PHPUnit"
        run: "vendor/bin/phpunit"

#      - name: "Send code coverage report to Codecov.io"
#        env:
#          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
#        run: "bash <(curl -s https://codecov.io/bash) || true"
